---
  - name: "STAGE_[ 7.1 of 18 ] --- create folder for vcloud CSI"
    file:
      path: "/home/{{ os_admin_username }}/k8s_addons/vcloud_csi"
      state: directory
      mode: '0644'
  # Create a Kubernetes Secret for vcloud Container Storage Plug-in
  # create vcloud-csi secret from a template
  - name: "STAGE_[ 7.2 of 18 ] --- create vcloud-csi secret manifest file from  template"
    template:
      src: ../templates/vcloud-basic-auth.yaml.j2
      dest: "/home/{{ os_admin_username }}/k8s_addons/vcloud_csi/vcloud-basic-auth.yaml"
      mode: '0644'
  - name: "STAGE_[ 7.3 of 18 ] --- create vcloud-csi config manifest file from  template"
    template:
      src: ../templates/vcloud-csi-config.yaml.j2
      dest: "/home/{{ os_admin_username }}/k8s_addons/vcloud_csi/vcloud-csi-config.yaml"
      mode: '0644'
  - name: "STAGE_[ 7.4 of 18 ] --- copy vcloud-csi manifests to vcloud_csi folder"
    copy:
      src: "../files/{{ item }}"
      dest: "/home/{{ os_admin_username }}/k8s_addons/vcloud_csi/{{ item }}"
      mode: '0644'
    loop:
      - csi-controller.yaml
      - csi-driver.yaml
      - csi-node.yaml
  # create storage class manifest
  - name: "STAGE_[ 7.5 of 18 ] --- create storage class manifest from  template"
    template:
      src: ../templates/storage_class_vcloud.yaml.j2
      dest: "/home/{{ os_admin_username }}/k8s_addons/vcloud_csi/storage_class.yaml"
      mode: '0644'     
  # apply vSphere Container Storage Plug-in manifests
  - name: "STAGE_[ 7.6 of 18 ] --- Deploy vcloud Container Storage Plug-in."
    kubernetes.core.k8s:
      kubeconfig: "/etc/kubernetes/admin.conf"
      state: present
      src: "/home/{{ os_admin_username }}/k8s_addons/vcloud_csi/{{ item }}"
    #        definition: "{{ lookup('template', '{{ item }}') }}"
    #      with_fileglob:
    #        - "/home/{{ os_admin_username }}/k8s_addons/vcloud_csi/*.yaml"
    loop:
      - csi-controller.yaml
      - csi-driver.yaml
      - csi-node.yaml
      - vcloud-basic-auth.yaml
      - vcloud-csi-config.yaml
      - storage_class.yaml
    tags: apply_csi_manifests

        