---
  - name:  "STAGE_[ 11.1 of 18 ] --- Add Ingress controller Server  Helm repo"
    kubernetes.core.helm_repository:
      name: ingress-nginx
      repo_url: "https://kubernetes.github.io/ingress-nginx"
    tags: 
      - ingress-repo
      - ingress-controller
  - name:  "STAGE_[ 11.2 of 18 ] --- Deploy Ingress controller"
    kubernetes.core.helm:
      name: ingress-nginx
      chart_ref: ingress-nginx/ingress-nginx
      release_namespace: ingress-nginx
      create_namespace: true
      kubeconfig: "/etc/kubernetes/admin.conf"
      values:
        controller:
          replicaCount: 3
          service:
            nodePorts:
              http: "{{ ingress_controller_nodeport_http }}"
              https: "{{ ingress_controller_nodeport_https }}"
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                      - ingress-nginx
                    - key: app.kubernetes.io/instance
                      operator: In
                      values:
                      - ingress-nginx
                    - key: app.kubernetes.io/component
                      operator: In
                      values:
                      - controller
                  topologyKey: kubernetes.io/hostname  
#       values_files:
#         - "/home/{{ os_admin_username }}/k8s_addons/ingress/ingress_controller_values.yaml"
    tags:
       - ingress-controller