---

  - name: "STAGE_[ 6.1 of 18 ] --- create folders"
    file:
      path: "/home/{{ os_admin_username }}/k8s_addons/calico"
      state: directory
      mode: '0644'
  - name: "STAGE_[ 6.2 of 18 ] --- download Calico tigera operator manifest"
    ansible.builtin.get_url:
      url: "https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/tigera-operator.yaml"
      dest: "/home/{{ os_admin_username }}/k8s_addons/calico"
      mode: '0644'
    tags: calico
  
  - name: "STAGE_[ 6.3 of 18 ] ---create Calico configuration manifest"
    template:
      src: ./templates/calico_config.yaml.j2
      dest: "/home/{{ os_admin_username }}/k8s_addons/calico/calico_config.yaml"
      mode: '0644'
    tags: calico
  - name: "STAGE_[ 6.4 of 18 ] --- download calicoctl"
    ansible.builtin.get_url:
      url: "https://github.com/projectcalico/calico/releases/download/{{ calico_version }}/calicoctl-linux-amd64"
      dest: "/usr/local/bin/calicoctl"
      mode: '0755'
    tags: calicoctl
  - name: "STAGE_[ 6.5 of 18 ] --- apply Tigera operator manifest"
    kubernetes.core.k8s:
      kubeconfig: "/etc/kubernetes/admin.conf"
      state: present
      src: "/home/{{ os_admin_username }}/k8s_addons/calico/tigera-operator.yaml"
  
  - name: "STAGE_[ 6.6 of 18 ] --- wait till Tigera operator replicas be greater than 0"
    shell: | 
      kubectl --kubeconfig=/etc/kubernetes/admin.conf -n tigera-operator get deployment tigera-operator -o jsonpath='{.status.availableReplicas}'
    register: tigera_replicas_available
    until: tigera_replicas_available.stdout | int > 0
    retries: 15
    delay: 10
    tags: wait_tigera
  - name: "STAGE_[ 6.7 of 18 ] --- apply Calico config manifest"
    kubernetes.core.k8s:
      kubeconfig: "/etc/kubernetes/admin.conf"
      state: present
      src: "/home/{{ os_admin_username }}/k8s_addons/calico/calico_config.yaml"

...
