---
  - name: create a folder for a tenant kubeconfig files
    file:
      path: "/home/{{ os_admin_username }}/k8s_addons/pki"
      state: directory
      mode: '0644'
    register: kubeconfig_path

  - name : create kubeconfig with single context for a tenant admin user scoped to default tenant namespace
    shell:
      kubectl config --kubeconfig="{{ kubeconfig_path['path'] }}/{{ tenant_k8s_admin_username }}-config" set-cluster poc_cluster \
        --server="https://{{ k8s_controlPlane_Endpoint }}:6443" \
        --certificate-authority=/etc/kubernetes/pki/ca.crt \
        --embed-certs
  - name: Add user details to kubeconfig
  
    shell:
      kubectl config --kubeconfig="{{ kubeconfig_path['path'] }}/{{ tenant_k8s_admin_username }}-config" set-credentials "{{ tenant_k8s_admin_username }}" \
        --client-certificate="/home/{{ os_admin_username }}/k8s_addons/pki/{{ tenant_k8s_admin_username }}.pem" \
        --client-key="/home/{{ os_admin_username }}/k8s_addons/pki/{{ tenant_k8s_admin_username }}-key.pem" \
        --embed-certs
  - name: Add context details to kubeconfig
    shell:
      kubectl config --kubeconfig="{{ kubeconfig_path['path'] }}/{{ tenant_k8s_admin_username }}-config" set-context namespace_admin \
        --cluster=poc_cluster \
        --namespace="{{ tenant_ns_default }}" \
        --user="{{ tenant_k8s_admin_username }}"

  - name: Set default context for the kubeconfig
    shell:
      kubectl config --kubeconfig="{{ kubeconfig_path['path'] }}/{{ tenant_k8s_admin_username }}-config" use-context namespace_admin
      
  - name: Display kubeconfig location
    debug:
      msg: "K8s Tenant kubeconfig file is here: {{ kubeconfig_path['path'] }}/{{ tenant_k8s_admin_username }}-config"
                                                                             

