---
  
    - name: "STAGE_[ 3.1 of 18 ] Download the Google Cloud public signing key"
      ansible.builtin.get_url:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: /etc/apt/keyrings/kubernetes-archive-keyring.gpg 
        mode: '0644'
      register: dnl_state
      until: dnl_state.failed == false
      retries: 100
      delay: 10
      tags: repoad        
    
    - name: "STAGE_[ 3.2 of 18 ] Add the Kubernetes apt repository"
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes
        update_cache: true
      tags:
        - repoadd
    
    #echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
    - name: "STAGE_[ 3.3 of 18 ] debug k8s_ver variable"
      debug:
        msg: "{{ k8s_ver }}"
      tags: kube_bin_install

    - name: "STAGE_[ 3.4 of 18 ] update apt"
      ansible.builtin.apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
        allow_downgrade: yes
      loop:
        - "kubectl={{ k8s_ver }}"
        - "kubeadm={{ k8s_ver }}"
        - "kubelet={{ k8s_ver }}"
      tags: kube_bin_install
          
    - name: "STAGE_[ 3.5 of 18 ] Hold kubeadm kubelet and kubectl versions - prevent auto updated and removes"
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    
